bundlename: smb.extension
filename: smb-extension
bundleversion: 1.0.0.
id: A35C8501-FFBB-43EA-975C6883C92A7D5E
luceeCoreVersion: 7.0.0.395
releaseType: server
appendix: -SNAPSHOT
label: SMB Resource Extension
description: SMB / CIFS Resource Provider Extension.
class: org.lucee.extension.resource.smb.SMBResourceProvider